---

services:
  lego:
    build:
      context: ./lego/
      args:
        ALPINE_VERSION: '3.20'
        GOLANG_VERSION: '1.22'
        LEGO_VERSION: 'v4.19.2'
    environment:
      DOMAINS: ${DOMAINS}
      EMAIL: ${EMAIL}
      RELOAD_PROCESSES_SIGHUP: ${RELOAD_PROCESSES_SIGHUP}
      RELOAD_PROCESSES_SIGUSR1: ${RELOAD_PROCESSES_SIGUSR1}
    volumes:
      - letsencrypt:/letsencrypt
    ports:
      # Used by TLS ALPN challenge
      - 443:443/tcp

  murmur:
    build:
      context: ./murmur/
      args:
        ALPINE_VERSION: '3.20'
        MURMUR_VERSION: '1.4.287-r11'
    volumes:
      - db:/data
      - logs:/logs
      - letsencrypt:/letsencrypt
      - ./murmur.conf:/murmur.conf:ro
    ports:
      - 64738:64738/tcp
      - 64738:64738/udp
    # Share the PID namespace of lego container
    # This allows lego to see the Murmur service and restart it
    pid: service:lego

volumes:
  db:
  letsencrypt:
  logs:
